-- Haskell data types for the abstract syntax.
-- Generated by the BNF converter.

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language MyLang.

module AbsMyLang where

import Prelude (Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Program = Prog [TopDef]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data TopDef = FnDef Type Ident [Arg] Block
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Arg = Argum Type Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Block = Bloc [Stmt]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Stmt
    = Empty
    | BStmt Block
    | Decl Type [Item]
    | ConstDecl Type [Item]
    | Ass Ident Expr
    | ArrAss Ident [Expr] Expr
    | Ret Expr
    | VRet
    | Cond Expr Stmt
    | CondElse Expr Block Block
    | While Expr Stmt
    | For Ident Expr Expr Stmt
    | Print [Expr]
    | Break
    | Continue
    | SExp Expr
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Item = NoInit Ident | Init Ident Expr | ArrayInit Ident [Expr]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Type = SimpleType SType | CollectionType CType
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data CType = Array SType
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data SType = Int | Str | Bool | Void
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Expr
    = EVar Ident
    | ELitInt Integer
    | ELitTrue
    | ELitFalse
    | EApp Ident [Expr]
    | EString String
    | EArr Ident [Expr]
    | Neg Expr
    | Not Expr
    | EMul Expr MulOp Expr
    | EAdd Expr AddOp Expr
    | ERel Expr RelOp Expr
    | EAnd Expr Expr
    | EOr Expr Expr
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data AddOp = Plus | Minus
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data MulOp = Times | Div | Mod
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data RelOp = LTH | LE | GTH | GE | EQU | NE | TR
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

