# Makefile generated by BNFC.

GHC        = ghc
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : Interpreter

# Rules for building the parser.

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

Interpreter : AbsMyLang.hs LexMyLang.hs ParMyLang.hs PrintMyLang.hs Interpreter.hs
	${GHC} ${GHC_OPTS} $@

# Rules for cleaning generated files.

clean :
	-rm -f *.hi *.o *.log *.aux *.dvi Interpreter

distclean : clean
	-rm -f AbsMyLang.hs AbsMyLang.hs.bak ComposOp.hs ComposOp.hs.bak DocMyLang.txt DocMyLang.txt.bak ErrM.hs ErrM.hs.bak LayoutMyLang.hs LayoutMyLang.hs.bak LexMyLang.x LexMyLang.x.bak ParMyLang.y ParMyLang.y.bak PrintMyLang.hs PrintMyLang.hs.bak SkelMyLang.hs SkelMyLang.hs.bak TestMyLang.hs TestMyLang.hs.bak XMLMyLang.hs XMLMyLang.hs.bak ASTMyLang.agda ASTMyLang.agda.bak ParserMyLang.agda ParserMyLang.agda.bak IOLib.agda IOLib.agda.bak Main.agda Main.agda.bak MyLang.dtd MyLang.dtd.bak TestMyLang LexMyLang.hs ParMyLang.hs ParMyLang.info ParDataMyLang.hs Makefile


# EOF
